// export const KEY_TRANSLATE = '$DGS/DASHBROAD_CHANGE_VALUE_ITEM'
export const KEY_TRANSLATE = 'CaptureMonitoring';
export const NAME_REDUCER = 'CaptureMonitoring';
export const TEST_CONNECT_REDUCER = '$DGS/TEST_CONNECT_REDUCER';
export const GET_LIST_DATA_CAPTURE_MONITORING = '$DGS/GET_LIST_DATA_CAPTURE_MONITORING';
export const SET_CAPTURE = '$DGS/SET_CAPTURE';
export const SET_SELECTED_CAPTURE = '$DGS/SET_SELECTED_CAPTURE';