// export const KEY_TRANSLATE = '$DGS/DASHBROAD_CHANGE_VALUE_ITEM'
export const KEY_TRANSLATE = 'CaptureMonitoring';
export const NAME_REDUCER = 'CaptureMonitoring';
export const GET_BATCH = '$DGS/GET_BATCH';
export const GET_DATA_IMPORTED_HISTORY = '$DGS/GET_DATA_IMPORTED_HISTORY';
export const GET_LIST_DATA_CAPTURE_MONITORING = '$DGS/GET_LIST_DATA_CAPTURE_MONITORING';
export const SET_CAPTURE = '$DGS/SET_CAPTURE';
export const SET_SELECTED_CAPTURE = '$DGS/SET_SELECTED_CAPTURE';