// export const KEY_TRANSLATE = '$DGS/DASHBROAD_CHANGE_VALUE_ITEM'
export const KEY_TRANSLATE = 'dashboard';
export const NAME_REDUCER = 'dashboard';
export const TEST_CONNECT_REDUCER = '$DGS/TEST_CONNECT_REDUCER';
export const GET_DATA_USERS = '$DGS/GET_DATA_USERS';
export const GET_DATA_USERS_ONLINE = '$DGS/GET_DATA_USERS_ONLINE';
export const GET_DATA_USERS_ASSIGN = '$DGS/GET_DATA_USERS_ASSIGN';
export const SET_USER_ASSIGN = '$DGS/SET_USER_ASSIGN';