export const MONITOR_LIST_SET_LIST = 'MONITOR_LIST_SET_LIST';
export const MONITOR_LIST_SET_VERSION_LIST = 'MONITOR_LIST_SET_VERSION_LIST';
export const MONITOR_LIST_ERROR = 'MONITOR_LIST_ERROR';

export const MONITOR_ITEM_EXPAND = 'MONITOR_ITEM_EXPAND';
export const MONITOR_ITEM_SET_ITEM = 'MONITOR_ITEM_SET_ITEM';
export const MONITOR_ITEM_SET_CANVAS = 'MONITOR_ITEM_SET_CANVAS';
export const MONITOR_ITEM_RESET = 'MONITOR_ITEM_RESET';

export const MONITOR_TABLE_SET_LIST_ACTIVITY_INSTANCES = 'MONITOR_TABLE_SET_LIST_ACTIVITY_INSTANCES';
export const MONITOR_TABLE_SET_LIST_BATCH_ID_INSTANCES = 'MONITOR_TABLE_SET_LIST_BATCH_ID_INSTANCES';
export const MONITOR_TABLE_SET_TASK_FIRST_INDEX = 'MONITOR_TABLE_SET_TASK_FIRST_INDEX';
export const MONITOR_TABLE_SET_TASK_SECOND_INDEX = 'MONITOR_TABLE_SET_TASK_SECOND_INDEX';
export const MONITOR_TABLE_RECLAIM = 'MONITOR_TABLE_RECLAIM';
export const MONITOR_TABLE_ASSIGN_USER = 'MONITOR_TABLE_ASSIGN_USER';
export const MONITOR_TABLE_GETTING = 'MONITOR_TABLE_GETTING';
export const MONITOR_TABLE_SET_STEP_FIRST = 'MONITOR_TABLE_SET_STEP_FIRST';
export const MONITOR_TABLE_SET_STEP_SECOND = 'MONITOR_TABLE_SET_STEP_SECOND';
export const MONITOR_TABLE_SHOW_POPUP = 'MONITOR_TABLE_SHOW_POPUP';
export const MONITOR_TABLE_HIDE_POPUP = 'MONITOR_TABLE_HIDE_POPUP';
export const MONITOR_TABLE_RESET = 'MONITOR_TABLE_RESET';

export const MONITOR_RESET = 'MONITOR_RESET';

export const MONITOR_USERS_SET_LIST = 'MONITOR_USERS_SET_LIST';
export const MONITOR_USERS_INPUT_CHANGE = 'MONITOR_USERS_INPUT_CHANGE';
export const MONITOR_USERS_FILTER= 'MONITOR_USERS_FILTER';
export const MONITOR_USERS_HIDE_POPUP= 'MONITOR_USERS_HIDE_POPUP';
export const MONITOR_USERS_SHOW_POPUP= 'MONITOR_USERS_SHOW_POPUP';
